version: '3.1'

services:
  postgresql:
    image: postgres:15.5
    container_name: "postgresql"
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
    networks:
      net:
        aliases:
          - postgresql
  halo_api:
    image: g14n/nginx-php:8.3.1
    container_name: "halo_api"
    restart: always
    environment:
      - ENVIRONMENT=development
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:7pWqb+DLKmhMIkjzNp5p9eWQI5QkuX4YK/lF1JBDRfs=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8101
      - DB_CONNECTION=pgsql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_DATABASE=halotek
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SWAGGER_VERSION=3.0
      - JWT_SECRET=qGU41rHobAicZXhkLxvvqsgJo1ilpX9nlqeOxC343LcUlnEuw6OdKAwOhxtbxGUa
      - JWT_TTL=10080
      - JWT_REFRESH_TTL=16000
    ports:
      - "127.0.254.1:8101:80"
    volumes:
      - ./www/api:/app
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/nginx/default.conf:/etc/nginx/http.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    tty: true
    networks:
      net:
        aliases:
          - halo_api
  halo_web:
    image: g14n/bun:alpine-1
    container_name: "halo_web"
    restart: always
    environment:
      - ENVIRONMENT=development
      - VITE_API_DEVELOPMENT_URL=http://127.0.254.1:8101
    ports:
      - "8100:5173"
    volumes:
      - ./www/web:/app
    tty: true
    command: "bun run dev"
    networks:
      net:
        aliases:
          - halo_api

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.0.120.0/24
          gateway: 172.0.120.254
